### ISSUE TITLE
add rights management to allow user access to different rdiff-backup locations

### ISSUE THREAD

**Issue by the2nd** [ikus060/rdiffweb#15]
IMHO it would be great have a simple rights management where it is possible to grant user access to different backup locations. maybe we could remove the per user "root directory" setting and make it an global setting for rdiffweb and then granting access to users on subdirectories?

**Comment by sudoman** [comment]
I'm interested in using this patch locally. Is there some reason it hasn't been merged upstream?

**Comment by ikus060** [comment]
It doesn't follow the direction I've taken for user permissions. Version
0.8 (next stable version) is using plugins to manage the permissions. I
didn't have time to integrate this feature within the plugin architecture.

--
Patrik Dufresne
