### ISSUE TITLE
i18n: installing .mo files

### ISSUE THREAD

**Issue by peyremorgan** [ikus060/rdiffweb#33]
_As of Tue 3 Feb 2015, this issue only affects the `i18n` branch_

It seems that translation files in the `locales` folder are not copied at installation since they are not in the `package_data['rdiffweb']` list in `main.py`.

I see two fixes to this issue:
* __The quick one:__ 
Adding `locales/fr/LC_MESSAGES/messages.mo` to said list
* __The future-proof one:__
Using a `MANIFEST.in` file to recursively add all .mo files in the `locales` directory

You are very welcome to comment if you face the same issue, or if you think this is a problem with my setup.
@ikus060, feel free to tell me which solution you'd prefer and to assign me to this issue if you will.

**Comment by ikus060** [comment]
Hi peyremorgan,

I'm not very familiar with the `MANIFEST.in`. Correct me if I'm wrong, this approach will have an impact to the installation procedure. From the `MANIFEST.in` we need to execute the command `sdist` to generate the `MANIFEST`. Or, Is there a way to execute this command when calling `build` ?

**Comment by peyremorgan** [comment]
Hi ikus060,

I have to admit i'm not very familiar with it neither. Based on some quick tests, i've found that the following changes caused the content of the `locales` folder to be copied alongside .py files (you can also [see them as a commit](https://github.com/peyremorgan/rdiffweb/commit/226bfd4a60cc1b4e60bb3d29badd7e4c9c48ef2b)).

```diff
diff --git a/MANIFEST.in b/MANIFEST.in
new file mode 100644
index 0000000..2f1f2d0
--- /dev/null
+++ b/MANIFEST.in
@@ -0,0 +1 @@
+recursive-include rdiffweb/locales *

diff --git a/setup.py b/setup.py
index 26f6770..defb977 100644
--- a/setup.py
+++ b/setup.py
@@ -46,8 +46,9 @@ setup(name='rdiffweb',
       data_files=[('/etc/rdiffweb', ['rdw.conf']),
                   ('/etc/init.d', ['init-script/rdiffweb'])
                   ],
+      include_package_data=True,
       entry_points={"console_scripts": ["rdiffweb = rdiffweb.main:start"]},
       install_requires=["CherryPy>=3.2.2",
                            "pysqlite>=2.6.3",
                         "Jinja2>=2.6"]
```

I've had nothing more to do than a regular `python setup.py install` for it to work. Tested on _Darwin 14.0.0 x86_64_ (Apple Macbook) and _Linux 3.4.6 armv5tel_ (Qnap TS212)

**Comment by ikus060** [comment]
It's seams fine. I will play a bit with it before going forward with `MANIFEST.in`. There are many complains about `include_package_data` not working with older version of setuptools. Yet, it's recommended to use either `include_package_data` or `package_data`...

**Comment by peyremorgan** [comment]
I appreciate that the Python distribution system is in a complete mess... The `MANIFEST.in` solution may be future-proof, but it is indeed not guaranteed to work everywhere _today_.

Another solution would be to require anyone contributing a translation to register the corresponding .mo file in `setup.py`. See [this commit](https://github.com/peyremorgan/rdiffweb/commit/cae68cf8ebed31bb1cf4fe0aa1eb3014d76e5a41) for a preview.

A third option would be to add these files to `package_data['rdiffweb']` at runtime using a function in `setup.py`. See [this commit](https://github.com/peyremorgan/rdiffweb/commit/93d001a5299c61ee7dfdec2e4c55530033bee339) for a preview. __Please note that this is untested, "alpha quality" code__

**Comment by ikus060** [comment]
Let keep it simple for now. I will accept your merge request with modifications to setup.py. So far this solution is working. It's only a pain to maintain each translation but a can live with it!

Thank for your time!

**Comment by peyremorgan** [comment]
Sorry I've been away for a couple of days. We might also have to mention in the `README.md` that new translations must be registered in `setup.py`. Would you like me to take care of that ?

Thank __you__ for your time!

**Comment by peyremorgan** [comment]
Is there a problem with my pull request? Tell me if there's something I can do to improve my patch. 

Thanks!

**Comment by ikus060** [comment]
Everything is fine with your merge request, but I want to test it in a DEV environment before merging. I didn't have time to do it yet... :-S

**Comment by ikus060** [comment]
Previous commit correct all the problem. Tested and work nicely on Debian.
