### ISSUE TITLE
Initial login admin/admin123 don't work

### ISSUE THREAD

**Issue by hasenstein** [ikus060/rdiffweb#36]
They result in

Warning! Invalid username or password.

EDIT: Okay I found /setup needs to be done first - this was not in the README on the webpage.

EDIT: Okay it is, I'm wrong.

**Comment by ikus060** [comment]
May you explain how you fix the problem ?

**Comment by hasenstein** [comment]
You have to start with the URL .../setup before you can do anything. That creates the admin user.
