### ISSUE TITLE
There is no information in the FAQ, README or anywhere in the GUI how to configure a location

### ISSUE THREAD

**Issue by hasenstein** [ikus060/rdiffweb#37]
I will have to look through the code to figure out how I add backup locations. This time I *did* check thoroughly before submitting the ticket. I think.

**Comment by hasenstein** [comment]
Sigh - I found it.

Okay, the concept that this is done per user and part of user configuration is not exactly obvious, at least it wasn't to me.

**Comment by ikus060** [comment]
Do you have a suggestion to improve the situation for new user ? I understand the concept is not very clear, it wasn't for me either 4 year ago... I might add this information in README file, in the FAQ and maybe within rdiffweb itself..

I'm reopening this bug

**Comment by hasenstein** [comment]
Add an FAQ section "How do I configure backup locations". Explain that the way the GUI works is that when you setup a user you can have exactly one directory for that user, and that should be either of a) a directory with multiple backup directories underneath, or b) one such backup directory. The only way to have multiple backup locations is a)

Good GUI design is much more difficult, I don't think I should even attempt to suggest how to make it clear "by design" what a new user needs to do.

**Comment by hasenstein** [comment]
It might be easier (in the GUI) if directories and users were "decoupled". It seems right now the user table also contains the directory. If it was two tables it would add flexibility (a user can have any number of backup directories anywhere), and there could be a "manage backup directories" button on the locations page. As it is such a button would create a conflict between DB and GUI design - right now managing the directories on the user admin page is consistent with how it seems to be stored in the DB.

**Comment by ikus060** [comment]
I add two section to the FAQ related to configuring the repositories:
http://www.patrikdufresne.com/en/rdiffweb/faq.html#what-is-a-repository
http://www.patrikdufresne.com/en/rdiffweb/faq.html#how-to-configure-the-repositories

I will probably modify the UI to provide some help regarding the configuration of repositories.

> It might be easier (in the GUI) if directories and users were "decoupled". It seems right now the user table also contains the directory. If it was two tables it would add flexibility (a user can have any number of backup directories anywhere), and there could be a "manage backup directories" button on the locations page.

It's related to issue #15.
