### ISSUE TITLE
Locations page occasionally shows all errors

### ISSUE THREAD

**Issue by hasenstein** [ikus060/rdiffweb#38]
When I reload the "Locations" page I occasionally get all errors. They disappear when I reload. When I repeat reloading from time to time I get another error.

![unbenannt-1](https://cloud.githubusercontent.com/assets/199179/6243916/f6257c56-b74b-11e4-941d-d4b821f28ec2.png)

![error](https://cloud.githubusercontent.com/assets/199179/6243917/f6280cbe-b74b-11e4-854e-fdac80445dbd.png)

**Comment by hasenstein** [comment]
Update: I get LOTS of errors but occasionally success when I browse through the repositories and backup history. But since I get occasional success it does not look like a setup error. I get

Error! The backup location does not exist.

But sometimes only after the 3rd reload, so initially it worked. When I repeat reloading the page I eventually get another success.

**Comment by peyremorgan** [comment]
Hi,

Thank you for taking the time to report this. You might find more information in `/var/log/rdiffweb.log`, including a more informative error message and what line of the program caused the error.

**Note**: *The logs may contain personal data such as filenames and usernames. Please review them before posting them.*
**Note**: *I am not an official maintainer of the project, I'm just trying to help. Views and opinions presented herein are solely mine.*

**Comment by ikus060** [comment]
The logs will greatly help as I never experience such a behaviour. When every repositories are in error, notice the front slash (/) before the location name. It's probably the source of the problem, since `/home-buha` represent a directory at the root `/`.

May you provide the value you sets for the location of this user ?

**Comment by hasenstein** [comment]
I'll add the logs, but I'll have to wait until my VPN client decides to cooperate once more. I can't get to the server right now...

**Comment by hasenstein** [comment]
Uploaded to https://gist.github.com/hasenstein/eef6c3c9a815196962c2

The error only happens for the admin user. I gave it the directory just above the 6 backup directories as home. A user that has one of those directories directly as home showed no errors.

**Comment by ikus060** [comment]
Thanks for the logs. With a quick look I see multiple error related to invalid repository. I will need to look closely to the source code and try to reproduce it.

Thanks alot for the info.

**Comment by hasenstein** [comment]
If you can't reproduce it I can run some debug code if necessary.

**Comment by ikus060** [comment]
1. I don't understand how a backup repository can't have an "increments" directory. Does "/var/backups/etc/rdiff-backup-data/increments" exists or not ? If it doesn't exists, your backup is most probably broken. Rdiff-backup is creating this directory. Unless I've miss something.
2. If your repository really exists and "increments" directory is available, it might be related to permissions issue in /var/backups/ directory. You may need to change the permissions or completely change the location to something like /home/rdiffweb/.

**Comment by hasenstein** [comment]
The backups work (I looked at previous files using rdiff-backup-fs and I also had to restore on eor the other file previously), and my backup directories are under /BACKUP. I have nothing under /var.

**Comment by hasenstein** [comment]
...and  /BACKUP/giorgio/home-mbe/rdiff-backup-data/increments exists, to give one example (I have six backup directories).

**Comment by ikus060** [comment]
Well if everything is under /backup there is something wrong  in your configuration. look at the log. Rdiffweb is expecting the backup locations to be under /var/backups. Check your users root directories.

**Comment by hasenstein** [comment]
I told rdiffweb the correct locations.

![unbenannt-1](https://cloud.githubusercontent.com/assets/199179/6422195/1adbac28-bed6-11e4-8e2c-916bc6b2a841.png)

**Comment by hasenstein** [comment]
Also: if the configuration was wrong it should not work EVER. But it works all the time for "mbe", and some of the time (by reloading the page without any other change) for "admin".

**Comment by ikus060** [comment]
Well, the log you post say very different. Is it possible to restart rdiffweb ?? Once stopped, make sure there is not a process running in the background: ps -ef l grep rdiffweb. Then kill it ...

Check the logs /var/log/rdiffweb.log for any error or reference to /var/backups/ you may post it again on gist.

**Comment by hasenstein** [comment]
> Well, the log you post say very different. 

So? Then it's a hard-coded path? I only configured it using the web interface. I'll restart.

**Comment by ikus060** [comment]
Nope its not hard coded. Never will and never was.

**Comment by hasenstein** [comment]
No more errors after restart. As I said, I only touched it through the web interface and only added the users shown. Anyway, good enough for me.

**Comment by ikus060** [comment]
Is it possible two instance of rdiffweb was running ? I'm glad your problem is fixed. Your feedback is welcome.

**Comment by hasenstein** [comment]
I only saw one in the process list. But the pid file contained an invalid PID, I had to kill it manually. Still, only one was running when I had the random errors before killing the one process and restarting it.

**Comment by ikus060** [comment]
I finally figure out why you had this problem. I manage to reproduce it. It was related to a cache of the user information. But the cache was not shared by every thread. Meaning, each thread was using it own cached. I've fix it in a local branches.

**Comment by hasenstein** [comment]
Great to hear something (even more) worthwhile (than me getting rid of the error) has come out of it :-)
