### ISSUE TITLE
Warning! can't determine if rdiffweb is configured! Check application log.

### ISSUE THREAD

**Issue by dnt83** [ikus060/rdiffweb#54]
Can't setup when install rdiffweb develop.
Warning! can't determine if rdiffweb is configured! Check application log.

**Comment by ikus060** [comment]
It would really help if you actually look at the log: /var/log/rdiffweb.log

Usually, this message is displayed when rdiffweb can't get references to the UserDB. The develop branch I've develop a new plugin architecture. If you kept your previous configuration file /etc/rdiffweb/rdw.conf you might miss some default configuration. Make sure you have the following in your config file:

    UserDB=SQLite
    SQLiteEnabled=True

**Comment by dnt83** [comment]
It's works, thank you very much @ikus060
