### ISSUE TITLE
update rdiffweb

### ISSUE THREAD

**Issue by kimthostrup** [ikus060/rdiffweb#58]
Hi,

This is not a issue as such, but a question to how I can update to the latest "release" ?

Thanks in advance.
/Kim

**Comment by ikus060** [comment]
Hello

To answer this question, please provide more detail about your current situation. What version are you currently running? What platform? Which version you want to install? Master: 0.7.1? or develop 0.8 ?

**Comment by ikus060** [comment]
Since you didn't provide further information, I'm closing this issue.
