### ISSUE TITLE
Support http and https out of the box

### ISSUE THREAD

**Issue by ikus060** [ikus060/rdiffweb#6]
According to user, rdiff-web required special configuration to support HTTPS. ref #5

I also configured https using the info from the wiki
http://www.rdiffweb.org/wiki/index.php?title=UsingHttps

**Comment by 88fingerslukee** [comment]
The wiki doesn't exist anymore that I can see. If you are landing here looking to enable HTTPS, you'll need to add the following two lines:

SSLCertificate=/path/to/certificate.file
SSLPrivateKey=/path/to/key.file

**Comment by ikus060** [comment]
I will add this information to the FAQ. But if you enable SSL in hope of adding security to rdiffweb, I'm strongly suggesting to add an Apache2 server in front of rdiffweb. cherrypy https is not the most secure. Have a look at https://www.ssllabs.com/ssltest/index.html
