### ISSUE TITLE
Run rdiffewb as a user other than root

### ISSUE THREAD

**Issue by sudoman** [ikus060/rdiffweb#60]
For the sake of security, it might be a good idea to run rdiffweb as a user other than root.

**Comment by sudoman** [comment]
i suppose that running as a non-root user may not work after all, since rdiff-backup files and directories have the uid and gid of the original source files. therefore chowning backup files to root:rdiffweb would break the backup. if this is not done, rdiffweb needs to be root in order to access all the files.

**Comment by ikus060** [comment]
Well, you may try to run rdiffweb under a different user.

e.g.: If you are using `backup-user` to run `rdiff-backup`, all your files should technically have owner define as `rdiff-backup`. So technically you may run rdiffweb as `backup-user` too.

Q: Why is rdiffweb is running as root ?
A: Historical reason. Previous version (develop by Josh Nisly) was running as root. I didn't bother to change the default settings.

**Comment by cweakland** [comment]
It looks like it can be done, I perform all my rdiff-backups as "backup-user", I then launch rdiffweb as backup-user, you need to give backup-user RWX access to /etc/rdiffweb, you also need to allow it to write to /var/log. Once this was done I was able to edit the service file and launch it normally, everything seems to work, here is my service file:

[Unit]
Description=Rdiffweb Server
Documentation=http://www.patrikdufresne.com/en/rdiffweb/

[Service]
User=backup-user
ExecStart=/usr/local/bin/rdiffweb

[Install]
WantedBy=multi-user.target

**Comment by ikus060** [comment]
@cweakland
The biggest limitation when running with different user then root is the file permissions on the repository. Those are created with a umask 0077. Which limit visibility to other user. 

You may also take a look at Minarca which solve many of those deployment issues
https://github.com/ikus060/minarca
