### ISSUE TITLE
Elapsed Time graph doesn't show units for days

### ISSUE THREAD

**Issue by Eeems** [ikus060/rdiffweb#71]
![image](https://user-images.githubusercontent.com/1176979/88302272-e40cfe80-ccc2-11ea-88ba-eb74f947c78a.png)
it looks like the graph doesn't properly parse units over an hour: [templates/graphs_times.html#L57-L64](https://github.com/ikus060/rdiffweb/blob/master/rdiffweb/templates/graphs_times.html#L57-L64)

**Comment by ikus060** [comment]
Thanks for reporting this issue. Will tale a look at it.
I had a plan to revamp the whole stats soon.

**Comment by ikus060** [comment]
Creating Merge Request in gitlab: https://gitlab.com/ikus-soft/rdiffweb/-/merge_requests/82
